name: crazy_quiz
description: "Crazy Time - Quiz Mystery"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.3.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    # SF-Pro-Display
    - family: SFR
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf